name: Check
on:
  push:
    branches:
      - "*"
jobs:
  dry-build:
    name: Dry Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: npm ci
      - run: npx --no-install next build
